version: 2
jobs:
  build:
    docker:
      # specify the version
      - image: circleci/golang:1.9

    working_directory: /go/src/github.com/fabioqcorreia/blog_example__go_web_app

    steps:
      - checkout
      - run: 
          command: go get -v -t -d ./...
      - run: 
          command: go test -v ./...
      - run: 
          command: go build