version: 2.1

parameters:
  image_registry: &image_registry us.gcr.io/vitaes/testapp:$CIRCLE_BRANCH

jobs:  
  build:
    docker:
      # specify the version
      - image: circleci/golang:1.9
      - image: *image_registry
        auth:
          username: _json_key
          password: $GCLOUD_SERVICE_KEY

    working_directory: /go/src/github.com/fabioqcorreia/blog_example__go_web_app

    steps:
      - checkout
      - run: 
        name: Installing depedencies
        command: go get -v -t -d ./...
      - run: 
        name: Running tests
        command: go test -v ./...
      - run: 
        name: Compiling
        command: go build
      - run:
        name: Building docker image
        command: docker build -t *image_registry .
      - run:
        name: Pushing docker image to gcr
        command: docker push *image_registry