version: 2.1

jobs:  
  build:
  
    working_directory: /go/src/github.com/fabioqcorreia/blog_example__go_web_app
  
    docker:
      # specify the version
      - image: circleci/golang:1.9

    steps:
      - checkout
      - setup_remote_docker
      - run: 
          name: Installing depedencies
          command: go get -v -t -d ./...
      - run: 
          name: Running tests
          command: go test -v ./...
      - run: 
          name: Compiling
          command: go build
      - run:
          name: Building docker image
          command: docker build -t us.gcr.io/vitaes/gosample:$CIRCLE_BRANCH .
      - run:
          name: Creating GCR json file
          command: echo $GCLOUD_SERVICE_KEY > /go/src/github.com/fabioqcorreia/blog_example__go_web_app/gcp-key.json
      - run:
          name: Login GCR
          command: cat gcp-key.json | docker login -u _json_key --password-stdin https://us.gcr.io/vitaes/
      - run:
          name: Pushing docker image to gcr
          command: docker push us.gcr.io/vitaes/testapp:$CIRCLE_BRANCH .

workflows:
  version: 2
  build_test_and_deliver:
    jobs:
      - build